// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTv7f8xdpobSoPJPKpZV77xQv6elpaif4',
    appId: '1:639735595481:web:ea4da0d2e1f9e13e1399c8',
    messagingSenderId: '639735595481',
    projectId: 'my-chat-ce',
    authDomain: 'my-chat-ce.firebaseapp.com',
    storageBucket: 'my-chat-ce.appspot.com',
    measurementId: 'G-5Q4S0YFSWP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1OMXbwG8Fjchjrzy9ODXfF3OY-39Yw98',
    appId: '1:639735595481:android:67cfc19fc462b93b1399c8',
    messagingSenderId: '639735595481',
    projectId: 'my-chat-ce',
    storageBucket: 'my-chat-ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw-4xJRkK3fzD5lDXL2cnADc08XvMz0tM',
    appId: '1:639735595481:ios:8d99edec130963aa1399c8',
    messagingSenderId: '639735595481',
    projectId: 'my-chat-ce',
    storageBucket: 'my-chat-ce.appspot.com',
    iosClientId: '639735595481-mg16h6rbd00ouadno8008kbvsredf2n3.apps.googleusercontent.com',
    iosBundleId: 'lk.ce.mychat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw-4xJRkK3fzD5lDXL2cnADc08XvMz0tM',
    appId: '1:639735595481:ios:615f3f5c9dc069bc1399c8',
    messagingSenderId: '639735595481',
    projectId: 'my-chat-ce',
    storageBucket: 'my-chat-ce.appspot.com',
    iosClientId: '639735595481-sth2duin8epnk25tgr9fo2fauvfvfcti.apps.googleusercontent.com',
    iosBundleId: 'lk.ce.mychat.RunnerTests',
  );
}
